### ISSUE TITLE
Make sure subsystems are all valid and add any missing ones

### ISSUE THREAD

**Issue by evanlucas** [evanlucas/core-validate-commit#9]
I know we are missing "inspector", not sure what else though.

**Comment by joaocgreis** [comment]
OS subsystems are missing, at least `win` should be included because it is a common and useful way of writing a clear commit message without having to waste chars with "... on Windows"

[`msi`](https://github.com/nodejs/node/commits/master/tools/msvs/msi), `etw` and `perfctr` should also be included.

**Comment by evanlucas** [comment]
This is now available in v3.1.0. Thanks!
